runtime: nodejs10

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 0
  target_cpu_utilization: 0.95

  max_concurrent_requests: 80
  target_throughput_utilization: 0.95

  min_idle_instances: 0
  max_idle_instances: 0

  min_pending_latency: 2000ms
  max_pending_latency: 2000ms
